[package]
name = "aoc"
version = "0.1.0"
authors = ["Michel van der Hulst <michel@voorkanter.com>"]

[workspace]

[dependencies]
day1 = { path = "day1" }
day2 = { path = "day2" }
day3 = { path = "day3" }
day4 = { path = "day4" }